# Generated by Django 5.1.6 on 2025-07-01 12:38

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('blog_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content')),
                ('blog_image', models.ImageField(upload_to='blogs/')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('meta_title', models.CharField(blank=True, help_text='Meta title for SEO', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO', null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for SEO', null=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-posted_on'],
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=200)),
                ('certificate_image', models.ImageField(upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Automatically Generate', max_length=200, null=True, unique=True)),
                ('service_title', models.CharField(max_length=200)),
                ('service_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content')),
                ('service_image', models.ImageField(upload_to='services/')),
                ('faq_question_1', models.CharField(blank=True, max_length=255, null=True)),
                ('faq_answer_1', models.TextField(blank=True, null=True)),
                ('faq_question_2', models.CharField(blank=True, max_length=255, null=True)),
                ('faq_answer_2', models.TextField(blank=True, null=True)),
                ('faq_question_3', models.CharField(blank=True, max_length=255, null=True)),
                ('faq_answer_3', models.TextField(blank=True, null=True)),
                ('faq_question_4', models.CharField(blank=True, max_length=255, null=True)),
                ('faq_answer_4', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscribe',
                'verbose_name_plural': 'Subscribes',
                'ordering': ['-created_at'],
            },
        ),
    ]
