# Generated by Django 5.1.6 on 2025-07-07 06:21

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Newsletter',
        ),
        migrations.AlterField(
            model_name='services',
            name='service_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
