# Generated by Django 5.1.6 on 2025-07-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_subscribe_newsletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='priority',
            field=models.IntegerField(default=5),
        ),
    ]
